services:
    -   
        name: ttyd
        port: 8081
        command: /usr/local/bin/ttyd -p 8081 tmux new -A -s gotty
        url: terminal.harshilgoel.tk
        uses_ws: True
        has_auth: True
    -   
        name: bots
        port: 8082
        command: cd /home/ubuntu/services/messengerbot/; pm2 start server.js
        url: bots.harshilgoel.tk
        uses_ws: False
        has_auth: False

